### ISSUE TITLE
Status Grid

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/cocoon#422]
Flutter widget that takes in results for commits, and shows them in a matrix. Should be able to scroll horizontally and vertically to show overflow.

## Milestones
- [X] Widget that can show a grid
- [X] Widget takes in List<CommitStatus> and shows it in the grid (CommitStatus imported from `app_dart/`)
- [ ] Widget is stateful and passes updates down to child widgets

**Comment by CaseyHillers** [comment]
#421 creates the StatusGrid widget with the ability to scroll on both axes when there is overflow.

Work still needs to be done on passing result data to the widgete.
